### ISSUE TITLE
doesn't work out of the box on windows

### ISSUE THREAD

**Issue by widp** [yutayamamoto/pdfoutline#6]
The script fails on windows due to two reasons
1) "/tmp/" directory doesn't exist on windows
  This can be fixed by using the tempfile python module
2) the ghostscript executable is not called 'gs' on windows and it is not in the windows "PATH" when  installed.
  One approach is to use argparse module for the all the arguments, including the ghostscript executable(this will be an optional argument).

**Comment by yutayamamoto** [comment]
Fixed by #7, now closing.
